### Question 2.1 Gauss Method

In [1]:
using LinearAlgebra
# using Plots
using PyCall
using PyPlot
using DataFrames
using CSV
# plotlyjs()

#### B1. Display Matrix Product
In Julia, computing a matrix product is trivial. Julia also makes sure that matrix dimensions are appropriate otherwise it throws an error

In [2]:
function Matrix_Mult_Show(M::Matrix,N::Vector)
    Mult=M*N
    print(Mult)
    return Mult
end

Matrix_Mult_Show (generic function with 1 method)

In [3]:
M=[1 2 3;
   4 5 6;
   7 8 9]
N=[10, 11, 12]
Matrix_Mult_Show(M,N);

[68, 167, 266]

#### B2. Solving the Equations for an Upper Diagonal Matrix
We have the following equations:
1. $x_1+2x_2+3x_3=10$
2. $~~~~~~~~~5x_2+6x_3=11$
3. $~~~~~~~~~~~~~~~~~~~~9x_3=12$

<br>
The LHS of this system of equations is an upper diagonal matrix. This can be easily solved:

In [4]:
M=[1 2 3;
   0 5 6;
   0 0 9]
N=[10,11,12];

This function starts from the last row of the diagonal and calculates $x_n$ as $\frac{N_n}{M_{n,n}}$.
<br><br>
Then it iterates from row $n-1$ to row $1$ and calculates $x_{n-i}$ as $\frac{N_i -\sum_j M_{i,j} x_j}{M_{i,i}} $. It returns an $n$ sized vector containing the solution for the system of equations

In [5]:
function Gauss_Method(M::Matrix,N)
    soln=zeros(size(N))
    soln[end] = (N[end]/M[end,:])[end]

    for i in (size(soln)[1]-1):-1:1
        ∑ax=0
        for j in (size(soln)[1]):-1:i+1
            ∑ax+=M[i,j]soln[j]
        end
        soln[i] = (N[i]-∑ax)/M[i,i]
        # print(i)
    end

    return soln
end

Gauss_Method (generic function with 1 method)

In [26]:
soln=Gauss_Method(M,N)
print("Solution vector x̄ for the given matrices:")
soln

Solution vector x̄ for the given matrices:

3-element Vector{Float64}:
 4.8
 0.6
 1.3333333333333333

#### Multiplying the upper diagonal matrix with the solutions we obtained matches the RHS of the original system of equations

In [ ]:
print("Verifying our solution:\n")
Matrix_Mult_Show(M,soln);

Verifying our solution:
[10.0, 11.0, 12.0]

### Question 2.2 Gaussian Elimination

#### Function for Gaussian Elimination without Pivoting

This function takes a matrix and converts it into an upper diagonal matrix which is then used by the function `Gauss_Method` to find the solutions. 

In [15]:
function Gauss_Solve(M::Matrix,B)
    M_UD=M
    for i in 1:size(M)[2]
        for j in i+1:size(M)[2]
            M_UD[j,:]-=M_UD[i,:]*M_UD[j,i]/M_UD[i,i]
        end
    end
    # show(M_UD)
    soln=Gauss_Method(M_UD,B)
    return soln
end

Gauss_Solve (generic function with 1 method)

The system of equations $M_2  X = N_2$ defined as matrices:<br>

In [ ]:
M2=[2     0.1   -0.2;
    0.05  4.2   0.032;
    0.12 -0.07  5]
N2 = [10, 11, 12];

In [31]:
soln2 = Gauss_Solve(M2,N2)
print("Solution vector x̄ for the given matrices:")
soln2

Solution vector x̄ for the given matrices:

3-element Vector{Float64}:
 5.109418104536006
 2.5995055268789558
 2.393933808799544

We Verify the solutions to the above equations. We get back the RHS of the system of equations as expected

In [32]:
print("Verifying our solution:\n")
Matrix_Mult_Show(M2,soln2)

Verifying our solution:
[10.0, 11.0, 12.000000000000002]

3-element Vector{Float64}:
 10.0
 11.0
 12.000000000000002